export const siteConfig = {
  name: "Edwin Leathers",
  shortName: "EL",
  brandLogo: "https://res.cloudinary.com/gpldwiup/image/upload/edwin/assets/logo.jpg",
  favicon: "https://res.cloudinary.com/gpldwiup/image/upload/w_64,h_64,c_fill,r_max/edwin/assets/logo.jpg",
  domain: "https://edwinleather.com",
  description:
    "Edwin Leathers — Handcrafted leather bags, wallets, belts & accessories made in India. Full-grain leather, designed to age beautifully. Free delivery on orders over ₹2,499.",
  shortDescription: "Handcrafted leather goods made in India. Bags, wallets, belts & accessories.",
  announcement: "Free delivery across India on orders over ₹2,499",
  shippingThreshold: 2499,
  supportEmail: "Support.edwinleather@gmail.com",
  phone: "+91 98978 63824",
  instagram: "https://www.instagram.com/edwin_the_leather_world/",
  storeName: "EDWIN Leather Store",
  mapsUrl: "https://www.google.com/maps/place/EDWIN+Leather+Store/data=!4m2!3m1!1s0x0:0x97eec2678cf14b96",
  currency: "INR",
  locale: "en-IN",
  keywords: [
    "leather bags India",
    "leather wallet for men",
    "genuine leather bags",
    "handcrafted leather goods",
    "leather belts for men",
    "leather accessories India",
    "handmade leather bags",
    "full grain leather",
    "premium leather goods",
    "leather tote bag",
    "leather laptop bag",
    "travel leather bag",
    "leather card holder",
    "leather key holder",
    "Edwin Leathers"
  ]
};
