export const siteConfig = {
  name: "Edwin Leathers",
  shortName: "EL",
  brandLogo: "https://res.cloudinary.com/gpldwiup/image/upload/w_64,h_64,c_fill,f_auto,q_auto/edwin/assets/logo.jpg",
  favicon: "https://res.cloudinary.com/gpldwiup/image/upload/w_64,h_64,c_fill,r_max/edwin/assets/logo.jpg",
  domain: "https://edwinleather.com",
  description:
    "Edwin Leathers — Handcrafted leather bags, wallets, belts & accessories made in India. Full-grain leather, designed to age beautifully. Free delivery on orders over ₹2,499.",
  shortDescription: "Handcrafted leather goods made in India. Bags, wallets, belts & accessories.",
  announcement: "Free delivery across India on orders over ₹2,499",
  shippingThreshold: 2499,
  supportEmail: "Support.edwinleather@gmail.com",
  phone: "+91 98978 63824",
  instagram: "https://www.instagram.com/edwin_the_leather_world/",
  storeName: "EDWIN Leather Store",
  mapsUrl: "https://www.google.com/maps/place/EDWIN+Leather+Store/data=!4m2!3m1!1s0x0:0x97eec2678cf14b96",
  currency: "INR",
  locale: "en-IN",
  keywords: [
    "leather bags India",
    "leather wallet for men",
    "genuine leather bags",
    "handcrafted leather goods",
    "leather belts for men",
    "leather accessories India",
    "handmade leather bags",
    "full grain leather",
    "premium leather goods",
    "leather tote bag",
    "leather laptop bag",
    "travel leather bag",
    "leather card holder",
    "leather key holder",
    "Edwin Leathers",
    "leather messenger bag for men",
    "leather duffle bag",
    "leather crossbody bag",
    "buy leather bags online India",
    "best leather wallet India",
    "leather clutch for men",
    "leather office bag",
    "leather travel accessories",
    "genuine leather belt for men",
    "handcrafted leather products Agra",
    "leather goods manufacturer India",
    "leather bags with free delivery",
    "leather backpack for men",
    "leather organizer wallet",
    "pure leather bags online",
    "leather bag price India",
    "leather wallet price India",
    "leather belt price India",
    "best leather bag brand India",
    "top leather goods store India",
    "leather goods online shopping",
    "leather bag for men price under 5000",
    "leather wallet for men price under 1000",
    "leather belt for men price under 1500",
    "buy leather wallet online India",
    "leather bag for women",
    "leather handbag India",
    "leather sling bag for women",
    "leather laptop sleeve",
    "leather passport holder",
    "leather travel wallet",
    "leather bow tie",
    "leather dog collar",
    "leather journal cover",
    "leather belt women",
    "leather bag offers India",
    "leather goods sale online",
    "best leather bags under 3000",
    "top quality leather bags India"
  ]
};
